### ISSUE TITLE
SL.predict annoying failure...

### ISSUE THREAD

**Issue by jlstiles** [ck37/superlearner-guide#1]
Just as it took the entire math/philosophy world something like 15 years to realize their definition of a set failed miserably due to Russell's paradox, this bug has gone on way too long...

`# This should not happen with SL.predict with a failed algorithm

# set up easy regression data
X = rnorm(100)
Y = 5*X + rnorm(100) + 2
X = data.frame(X = X)

# set up bad algorithm
SL.nothing = function(x) {x}

# declare the library
SL.library = c("SL.glm", "SL.nothing")

# call superlearner with bad alg in library
fit = SuperLearner(Y, X, family = gaussian, SL.library = SL.library)

# SL.predict breaks
preds = fit$SL.predict[1:100]

# library.predict still fine
fit$library.predict

# And this work around breaks if only one learner works 
preds = fit$library.predict[,fit$coef != 0] %*% fit$coef[fit$coef != 0] 

# So I code the following--maybe dumb and inefficient but works
if (length(fit$coef[fit$coef != 0]) == 1) {
  preds = fit$library.predict[,fit$coef != 0]
} else {
  preds = fit$library.predict[,fit$coef != 0] %*% fit$coef[fit$coef != 0]  
}

preds
`

**Comment by ck37** [comment]
Thanks, do you mind just copy-and-pasting this into the SuperLearner issue queue: https://github.com/ecpolley/SuperLearner/issues

**Comment by jlstiles** [comment]
yes, sorry it's early!

**Comment by ck37** [comment]
No prob at all; closing this one since it's posted to the SL issue queue now.
