### ISSUE TITLE
include HAL maybe, it works and is stellar...

### ISSUE THREAD

**Issue by jlstiles** [ck37/superlearner-guide#2]
I have been using David's SL wrapper for hal that comes with his package:

if (!require(devtools)) install.packages(devtools)
devtools::install_github("benkeser/halplus")

It is a fabulous wrapper so maybe we can just include it with a warning in the vignette that one should time it first before putting it in the library.  Anyway, I'm sure that HAL with screeners will also be excellent even if dimension is high.

**Comment by ck37** [comment]
Closing this one since it's posted to the SL issue queue now.
